{% set name = "benchmark" %}
{% set version = "1.6.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/google/benchmark/archive/v{{ version }}.tar.gz
  sha256: 6132883bc8c9b0df5375b16ab520fac1a85dc9e4cf5be59480448ece74b278d4

build:
  number: 0

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - test -f $PREFIX/include/benchmark/benchmark.h  # [unix]
    - if not exist %LIBRARY_INC%\\benchmark\\benchmark.h exit 1  # [win]
    - test ! -f $PREFIX/lib/libbenchmark.a  # [unix]
    - test ! -f $PREFIX/lib/libbenchmark_main.a  # [unix]
    - test -f $PREFIX/lib/libbenchmark${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libbenchmark_main${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\lib\\benchmark.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\benchmark_main.lib exit 1  # [win]

about:
  home: https://github.com/google/benchmark
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A microbenchmark support library

extra:
  recipe-maintainers:
    - xhochy
    - wesm
    - pitrou
    - kszucs
    - saraedum
