{% set version = "1.9.0" %}

package:
  name: benchmark
  version: {{ version }}

source:
  url: https://github.com/google/benchmark/archive/v{{ version }}.tar.gz
  sha256: 35a77f46cc782b16fac8d3b107fbfbb37dcd645f7c28eee19f3b8e0758b48994

build:
  number: 0

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}

test:
  commands:
    # presence of shared libs
    - test -f $PREFIX/lib/libbenchmark.so                       # [linux]
    - test -f $PREFIX/lib/libbenchmark.dylib                    # [osx]
    - test -f $PREFIX/lib/libbenchmark_main.so                  # [linux]
    - test -f $PREFIX/lib/libbenchmark_main.dylib               # [osx]
    - if not exist %LIBRARY_BIN%\benchmark.dll exit 1           # [win]
    - if not exist %LIBRARY_LIB%\benchmark.lib exit 1           # [win]
    - if not exist %LIBRARY_BIN%\benchmark_main.dll exit 1      # [win]
    - if not exist %LIBRARY_LIB%\benchmark_main.lib exit 1      # [win]

    # absence of static libs (unix)
    - test ! -f $PREFIX/lib/libbenchmark.a                      # [unix]
    - test ! -f $PREFIX/lib/libbenchmark_main.a                 # [unix]

    # headers
    - test -f $PREFIX/include/benchmark/benchmark.h             # [unix]
    - if not exist %LIBRARY_INC%\benchmark\benchmark.h exit 1   # [win]

about:
  home: https://github.com/google/benchmark
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A microbenchmark support library

extra:
  recipe-maintainers:
    - xhochy
    - wesm
    - pitrou
    - kszucs
    - saraedum
