travis:
  secure:
    BINSTAR_TOKEN: RCVjxqPR5zAjDsKW9Vrq/zfNMMHD0egIRWVWPpWqoVRhBTCTvdyWsDeHxr3xD/F/7FhNDjlnQTrhPKXu90EWS0eRezA969KiDEX3HH0IbSfKUznNr9Vug0LQvlvWxNVE6CT8H3jkIeuX3KLsC1xjdD9E0iLu0Bu3TVo6p+DVPsyTx+ZdbrbY/WCqA9UtNRgvrjOsV5xHIMPG127+xxQFHjgI2WLpO8TMfjjq657CYMGd38PUe+GfcW6XKfqxycgDbDisI3C9cYGr2k2mwqIPauZTtTSvh8kH0lHtC5kp/aw0FDVNYWtpTFt8vRoaqcjl1BZTFUNVWgz/Mwhas4majxc+/2YDBxmEYMO4BPl0RzPZMxc7rKesDYoe6FFv04m34//N/4IZFNDWmWDB9gG2G2kvkdyRmLNHBTQtWo2RMbipUAXq8t7pTd5RbJ3mpj70a21l32LCgT7RVVAoh6iaC8gvTr/JpXzzxfnQV8pYbOrKtoFjBFmF0QImdwmcaCYFwNGuTPFdHkFHOyq/9/h3weojTkEyZGBYYDQ9UnrLX8D55j9zNoE78lazAZKwaKB7SQiZm8vEuuNSblw5Di9n3MLMT9ki80Ka3YOLS1HhpfaLh7ZfCQFvI/VwXNoXw9DoaEdsHiruWJODicHx/lgEYtxbAxnR7EbeW0EflHDw8G4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  linux_aarch64: default
  win: azure
conda_forge_output_validation: true
